### ISSUE TITLE
Utilização em addon Stremio

### ISSUE THREAD

**Issue by mrcanelas** [felipemarinho97/busca-legendas-api#1]
Olá cara tudo bem? incrível sua API, gostaria de usar ela em um addon para o Stremio, mas estou com problemas com o modulo do request, pode me ajudar a subir isso pra um servidor próprio? pode me adicionar no discord pra trocara uma ideia? mrcanelas#3552

**Comment by felipemarinho97** [comment]
Vc usou o node_modules built in?
Eu lembro que no tempo fiz umas modificações diretamente nas dependências do node
